### ISSUE TITLE
Travis CI ?

### ISSUE THREAD

**Issue by eddelbuettel** [NYTimes/gun-sales#10]
Shall we enable continuous integration via Travis CI?

I have it working [over here as you can in this diff](https://github.com/NYTimes/gunsales/compare/master...eddelbuettel:master)  which I did in my older fork because one has to give Travis CI read access to the repo -- which I cannot do here (your repo) but was able to do over on my side.

I am a big fan of continuous integration. It catches simple little errors _fast_ which is a good thing, and keeps a tab on ongoing quality.  I would be in very much in favour, but I cannot really send a PR before you agree to turn this on (and if you are agreeing in principle but are confused about the step I would be glad to walk you through over a hangout or phone call).

**Comment by gka** [comment]
I was not expecting "continuous" code changes in this repository and therefor I didn't think much of testing, but I'm fine with Travis if I don't have to put work into it. Merged your PR.

thanks for your effort.

**Comment by eddelbuettel** [comment]
I am not sure that you understand that you **need to enable Travis support for this repo at Travis**. Per [this page at Travis](https://travis-ci.org/NYTimes) the NYTimes account has five repos there.  This would be sixth.

I think it makes sense so that we eg get tests when you expand the data set as you do every few weeks.

**Comment by eddelbuettel** [comment]
Ahhhh, and I missed that you had turned it on!  Many thanks, @gka -- [here is the first check](https://travis-ci.org/NYTimes/gunsales). Appreciate the follow-up!
