### ISSUE TITLE
CRAN upload?

### ISSUE THREAD

**Issue by eddelbuettel** [NYTimes/gun-sales#6]
@gka @joshkeller, 

The package is ready:  `R CMD check --as-cran` passes without any issues for R-release and R-devel; the dependencies are all uploaded and available in binary.  I also sent it to [win-builder](http://win-builder.r-project.org) where it was processed just fine; results are available for [r-release](http://win-builder.r-project.org/1iBvtdb4G9u0) and [r-devel](http://win-builder.r-project.org/CbgyluLERbCd/) (but will disappear withing 72 hours).

So I think this is ready to be uploaded.  I currently have my name in `DESCRIPTION` as Maintainer: but it really is your package.  Do you want to change the name and upload, and or there reasons (too busy, too much paperwork, ...) why you'd want me to upload it?   I'd be happy to, but I want to make sure I am not seen as 'taking it' it from you.

**Comment by gka** [comment]
I don't have a problem with not being the maintainer. I see that we're mentioned as authors. And you did a lot of work converting our R code into a proper R package.

**Comment by eddelbuettel** [comment]
Yes, setting this up as coauthors -- you two for the analysis code that started it all, and me for packaging mechanics and the ggplot layer -- is perfectly fine.  I also have a decent working relationship with CRAN gatekeepers which may help (not that I think it is needed).

So the remaining question is:  Any more work we'd need to make _now_ before uploading? I will await your response to #1 to see that everything works at your end.

(One minor thing I am thinking of/suggesting is to create png versions of the ggplot charts and adding them to the README --- unless you prefer the base graphs because that is what went to production etc pp)

**Comment by gka** [comment]
Haha, there was an easy fix to this problem ;-) 

``` R
> needs(knitr, zoo, data.table)
```

With that I was able to simply

``` R
> R CMD install .
```

Now I can open a new R shell and run

``` R
> library(gunsales)
> analysis()
```

And it works.

Your `gganalysis` does not, however:

``` R
> gganalysis()
Error in as.Date.default(as.yearmon(index(ztotal))) : 
  do not know how to convert 'as.yearmon(index(ztotal))' to class “Date”
```

**Comment by gka** [comment]
just realized I posted the reply to the wrong issue, was meant to go on #1

**Comment by eddelbuettel** [comment]
Doesn't matter to me.  In order and briefly:
1. Yes, you need to have `knitr` installed to produce vignettes. I should have made that clearer. It is not a Depends: of the package as we do not need for normal operation of the package.
2.  Let me take the other side of the `needs()` call. I am not a fan of non-standard local reinvention of the package system.  I'd call this needs a `install.packages("knitr")`.
3. Correct, and my bug. The `gganalysis()` function needs to load the `zoo` package. So make sure you have it:

``` r
install.packages("zoo")
library(zoo)
```

after which this will work.

**Comment by gka** [comment]
Also, no hard feelings against `ggplot`, but I think I'd prefer `theme_bw()` as the default ggplot theme is just terrible (and probably the main reason why I don't use it more)

**Comment by eddelbuettel** [comment]
Hehe.

I am good friends with Hadley, but generally do not use his packages -- not a fan of `%>%` and always found `ggplot()` too slow. I am starting to like some of the defaults though.  There simply is too much whitespace around the base plots, and the per-state plots _really_ wanted to be faceted (for which I usually deploy `lattice`).  I'll look into `theme_bw()`

**Comment by gka** [comment]
think this can be closed, right? gunsales is on CRAN.

**Comment by eddelbuettel** [comment]
gunsales is NOT on CRAN because you never got back (hence a lack of consensus) to so I never uploaded.

I still plan to do it.

**Comment by eddelbuettel** [comment]
It is now in the queue at CRAN after I made a few more changes -- mostly [showing the charts in README.md](https://github.com/eddelbuettel/gunsales) -- but some more minor ones all of which are now in PR #13 for you to reruse.  I'll update here when I hear back from Vienna.

**Comment by eddelbuettel** [comment]
And following [one more accomodation to CRAN](https://github.com/eddelbuettel/gunsales/commit/5ddeb35944513de42e0f46feddafd49ef3b75db3) we are [now on CRAN](cran.r-project.org/package=gunsales) !!  Chapeau, and three cheers for @gka, @joshkeller and me :grinning: 

So we can close this one now.
